######################################################################
# Automatically generated by qmake (2.01a) lun. déc. 1 10:55:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += \
    viewer.h \
    scene.h \
    node.h \
    edge.h
SOURCES += app.cpp \
    viewer.cpp \
    scene.cpp \
    node.cpp \
    edge.cpp

FORMS += \
    viewer.ui \
    scene.ui
